import {Component} from '@angular/core';
import {Platform, PopoverController} from 'ionic-angular';
import {ApiService} from '../../services/api.service';
import {Tome} from '../../services/models';
import {UnsubscribingComponent} from '../unsubscribing.component';

@Component({
    selector: 'page-search',
    templateUrl: './search.html'
})
export class SearchPage extends UnsubscribingComponent {
    author: string;
    desc: string;
    keywords: string;
    kind: string;
    fulltext: string;
    availableTypes: string[] = [];
    availableBooks: Tome[] = [];
    results: Tome[] = [];
    displays = 10;

    showSections = false;
    possibleKeywords = {
        'ACCORD DE SCHENGEN': ['Etrangers'],
        'ACTE DE MARIAGE': ['Communes'],
        'ACTE DETACHABLE': ['Compétence'],
        'ACTE INDIVIDUEL': ['Compétence'],
        'ADMINISTRATION DE L\'EMPLOI': ['Travail'],
        ADOPTION: ['Noms et prénoms', 'Etrangers', 'Lois et règlements', 'Actes administratifs'],
        'AGENCE IMMOBILIERE': ['Autorisation d\'établissement'],
        'AGENCE DE VOYAGES': ['Autorisation d\'établissement'],
        'AIDES AUX ENTREPRISES': ['Autorisation d\'établissement'],
        'AIDES AU LOGEMENT': ['Logement'],
        'AIDES AU REEMPLOI': ['Travail'],
        'AIDES SOCIALES': ['Etrangers', 'Procédure contentieuse'],
        'AIDE-SOIGNANT': ['Autorisation d\'établissement', 'Santé publique'],
        'AMENAGEMENT DU TERRITOIRE': ['Urbanisme', 'Environnement'],
        ANNULATION: ['Recours en annulation'],
        'ANTENNES GSM': ['Etablissements classés', 'Urbanisme', 'Procédure contentieuse'],
        APATRIDES: ['Etrangers'],
        APPEL: ['Procédure contentieuse'],
        ARCHITECTES: ['Autorisation d\'établissement'],
        ARMEE: ['Fonction publique'],
        ARTISTES: ['Actes administratifs', 'Etrangers'],
        'ASSISTANCE JUDICIAIRE': ['Procédure contentieuse'],
        'ASSOCIATION SANS BUT LUCRATIF': ['Procédure contentieuse', 'Tutelle administrative'],
        ASSURANCES: ['Autorisation d\'établissement', 'Régulation économique'],
        'AUTONOMIE LOCALE': ['Communes'],
        'AUTORISATION DE SEJOUR': ['Etrangers'],
        'AUTORISATION DE TRAVAIL': ['Travail'],
        'AUTORITE ADMINISTRATIVE': ['Actes administratifs'],
        'AUTORITE DE LA CHOSE JUGEE': ['Procédure contentieuse'],
        'AVANCEMENT': ['Fonction publique'],
        AVION: ['Transports'],
        AVIS: ['Actes administratifs', 'Procédure administrative non contentieuse'],
        'AVOCAT': ['Procédure contentieuse', 'Actes réglementaires', 'Compétence'],
        'BANQUE (CONTROLE)': ['Régulation économique'],
        'BANQUE ET CAISSE D\'EPARGNE DE L\'ETAT': ['Fonction publique'],
        'BANQUE EUROPEENNE D\'INVESTISSEMENT': ['Compétence'],
        'BIBLIOTHEQUE CENTRALE DE LA MAGISTRATURE': ['Actes administratifs', 'Compétence'],
        BOURGMESTRE: ['Commune'],
        BOURSE: ['Compétence', 'Pratiques commerciales'],
        'BRUIT': ['Environnement', 'Etablissements classés'],
        'BUDGET': ['Finances publiques'],
        'CADASTRE DES LOYERS': ['Communes'],
        'CADUCITE D\'UN ACTE ADMINISTRATIF': ['Actes administratifs'],
        'CAISSES DE MALADIE': ['Santé publique'],
        'CEINTURE DE SECURITE': ['Droits de l\'homme', 'Lois et règlements', 'Transports'],
        'CENTRE COMMERCIAL': ['Autorisation d\'établissement'],
        'CENTRE HOSPITALIER': ['Fonction publique'],
        'CENTRE THERMAL': ['Actes administratifs'],
        'CHAMBRE DE COMMERCE': ['Actes réglementaires', 'Travail'],
        'CHAMBRE PROFESSIONNELLE': ['Elections', 'Travail (v. aussi Compétence', 'Impôts', 'Procédure contentieuse)'],
        'CHANTIER (FERMETURE DE)': ['Urbanisme', 'Procédure administrative non contentieuse'],
        CHASSE: ['Environnement'],
        'CHEMINS DE FER': ['Voirie'],
        'CHEMIN FORESTIER': ['Environnement'],
        'CHOMAGE': ['Compétence', 'Travail'],
        CIRCULAIRE: ['Lois et règlements', 'Actes réglementaires'],
        'COLLEGE VETERINAIRE': ['Actes administratifs'],
        'COMITE MIXTE D\'ENTREPRISE': ['Travail'],
        'COMMERCE (LIBERTE DU)': ['Autorisation d\'établissement', 'Régulation économique'],
        'COMMISSION D\'AMENAGEMENT': ['Urbanisme'],
        'COMMISSAIRE SPECIAL': ['Procédure contentieuse'],
        'COMMISSION CONSULTATIVE POUR LES ETRANGERS': ['Etrangers'],
        'COMMISSION DE SURVEILLANCE DU SECTEUR FINANCIER (CSSF)': ['Actes administratifs', 'Fonction publique'],
        'COMMISSION ROGATOIRE': ['Entraide judiciaire'],
        COMMUNES: ['aussi Procédure contentieuse'],
        'CONCESSION DE SERVICE PUBLIC': ['Marchés publics', 'Postes et Télécommunications'],
        CONCURRENCE: ['Pratiques commerciales'],
        'CONFIANCE LEGITIME': ['Lois et règlements'],
        'CONGE (de recreation)': ['Fonction publique'],
        'CONGE SYNDICAL': ['Travail'],
        'CONSEIL DE LA CONCURRENCE': ['Pratiques commerciales'],
        'CONSEIL DE PRESSE': ['Procédure contentieuse'],
        CONSIGNATION: ['Finances publiques', 'Impôts'],
        CONSTITUTION: ['Lois et règlements', 'Compétence', 'Procédure contentieuse'],
        'CONSTITUTIONNALITE D\'UNE LOI': ['Procédure contentieuse'],
        'CONSTITUTION D\'AVOCAT': ['Procédure contentieuse'],
        CONSTRUCTION: ['Urbanisme', 'Environnement'],
        'CONTRADICTOIRE (PRINCIPE DU)': ['Procédure administrative non contentieuse'],
        'CONTRAT (liberte de contracter)': ['Actes administratifs', 'Compétence',
            'Procédure administrative non contentieuse', 'Recours en annulation'],
        'CONTRAT DE TRAVAIL': ['Travail'],
        CONTRIBUTIONS: ['Impôts'],
        'CONTROLE DES BANQUES': ['Régulation économique'],
        'CONTROLE TECHNIQUE': ['Transports'],
        'CONVENTION INTERNATIONALE (en general)': ['Lois et règlements'],
        'CONVENTION DE GENEVE': ['Etrangers'],
        'CONVENTION EUROPEENNE DES DROITS DE L\'HOMME': ['Droits de l\'homme'],
        'CONVENTION RELATIVE AUX DROITS DE L\'ENFANT': ['Droits de l\'homme'],
        'COORDINATEUR DE SECURITE': ['Autorisation d’établissement'],
        'COTISATIONS PROFESSIONNELLES': ['Compétence', 'Travail (chambres professionnelles)'],
        'COURS D\'EAU': ['Environnement'],
        CRECHE: ['Santé publique'],
        'CURAGE D\'UN COURS D\'EAU': ['Environnement'],
        'DATE D\'APPRECIATION D\'UNE SITUATION ADMINISTRATIVE': ['Actes administratifs', 'Recours en annulation'],
        'DEBIT DE BOISSONS': ['Autorisation d\'établissement'],
        'DEBOISEMENT': ['Environnement'],
        DECHARGE: ['Environnement', 'Etablissements classés'],
        DECHETS: ['Environnement', 'Etablissements classés'],
        'DECISION ADMINISTRATIVE': ['Actes administratifs'],
        'DECISION INDIVIDUELLE': ['Actes administratifs', 'Compétence'],
        'DECISIONS SUSCEPTIBLES DE RECOURS': ['Actes administratifs'],
        'DEFAUT': ['Procédure contentieuse'],
        DELAIS: ['Procédure contentieuse', 'Procédure administrative non contentieuse'],
        'DELEGATION DE POUVOIR': ['Actes administratifs', 'Etrangers', 'Procédure contentieuse'],
        'DELEGATION DE SIGNATURE': ['Actes administratifs', 'Etrangers', 'Procédure contentieuse'],
        'DELEGATION DU PERSONNEL': ['Fonction publique', 'Travail'],
        'DEMANDE NOUVELLE': ['Procédure contentieuse, sub Echange de mémoires'],
        DETENTION: ['Actes administratifs', 'Droits de l\'homme', 'Etrangers'],
        'DETOURNEMENT DE POUVOIR': ['Recours en annulation'],
        'DIPLOMATIQUES (AGENTS)': ['Fonction publique'],
        DIPLOME: ['Autorisation d\'établissement', 'Enseignement'],
        DIRECTIVE: ['Lois et règlements', 'Actes réglementaires', 'Etrangers (régularisation des sans-papiers'],
        DISCIPLINE: ['Fonction publique', 'Postes et Télécommunications'],
        DISCOTHEQUE: ['Etablissements classés'],
        DISCRIMINATION: ['Fonction publique'],
        'DISCRETIONNAIRE (POUVOIR)': ['Recours en annulation', 'Fonction publique'],
        'DOMAINE PRIVE/PUBLIC': ['Voirie'],
        DOMICILE: ['Fonction publique', 'Impôts (domicile fiscal)', 'Noms – Prénoms – Domicile – Etat civil – Nationalité'],
        'DROITS ACQUIS': ['Actes administratifs', 'Urbanisme'],
        'DROITS DE LA DEFENSE': ['Droits de l\'homme'],
        'DROITS DE L\'HOMME': ['Etrangers', 'Fonction publique'],
        'DROITS DE L\'ENFANT': ['Droits de l\'homme'],
        'DROITS SUBJECTIFS': ['Compétence'],
        EAU: ['Environnement'],
        'ECHANGE DE RENSEIGNEMENTS': ['Impôts'],
        EDUCATEUR: ['Autorisation d\'établissement'],
        'EDUCATION NATIONALE': ['Enseignement'],
        'effet suspensif du recours': ['Procédure contentieuse'],
        'EGALITE DE TRAITEMENT': ['Fonction publique'],
        'EGALITE DEEVANT LA LOI': ['Lois et règlements'],
        ELECTIONS: ['aussi Travail'],
        'ELECTRICITE (CONTROLE DU MARCHE)': ['Régulation économique'],
        EMPLOYES: ['Travail', 'Fonction publique', 'Compétence'],
        'ENFANT (DROITS DE L\')': ['Droits de l\'homme'],
        'ENLEVEMENT INTERNATIONAL D\'ENFANTS': ['Droits de l\'homme'],
        ENQUETE: ['Procédure contentieuse'],
        'ENSEIGNES PUBLICITAIRES': ['Sites et monuments'],
        EOLIENNES: ['Environnement', 'Etablissements classés'],
        'ETABLISSEMENT': ['Autorisation d’établissement'],
        'ETABLISSEMENTS DANGEREUX, INSALUBRES OU INCOMMODES': ['Etablissements classés'],
        'ETAT CIVIL': ['Noms – Prénoms – Domicile – Etat civil – Nationalité'],
        EXAMENS: ['Autorisation d\'établissement', 'Enseignement'],
        'EXERCICE D\'UNE PROFESSION': ['Autorisation d\'établissement'],
        'EXECUTION DES JUGEMENTS ET ARRETS': ['Procédure contentieuse'],
        'EXECUTION DES PEINES': ['Actes administratifs', 'Compétence'],
        EXHUMATION: ['Communes'],
        'EXPERTS-COMPTABLES': ['Autorisation d\'établissement'],
        'EXPROPRIATION POUR CAUSE D\'UTILITE PUBLIQUE': ['Actes réglementaires', 'Droits de l\'homme'],
        EXPULSION: ['Etrangers', 'Droits de l\'homme'],
        EXTRADITION: ['Entraide judiciaire', 'Droits de l\'homme'],
        FAILLITE: ['Autorisation d\'établissement', 'Travail', 'Impôts'],
        'FERMETURE DE CHANTIER': ['Urbanisme', 'Procédure administrative non contentieuse'],
        FONCTIONNAIRES: ['Fonction publique', 'Postes et Télécommunications'],
        FONDATIONS: ['Tutelle administrative'],
        'FONDS D\'INVESTISSEMENT': ['Régulation économique'],
        FORAGE: ['Etablissements classés', 'Environnement'],
        'FORCE PUBLIQUE': ['Fonction publique'],
        'FORET': ['Environnement'],
        'FORME D\'UN ACTE ADMINISTRATIF': ['Actes administratifs'],
        'FORTUNE (IMPOT SUR LA)': ['Impôts'],
        FRAIS: ['Procédure contentieuse'],
        'FRAIS DE ROUTE': ['Fonction publique'],
        'GARANTIE DES SALAIRES': ['Travail'],
        GARDIENNAGE: ['Actes réglementaires', 'Autorisation d\'établissement'],
        'GOUVERNEMENT DEMISSIONNAIRE': ['Compétence'],
        'GRANDES SURFACES COMMERCIALES': ['Autorisation d\'établissement'],
        GREVE: ['Actes administratifs', 'Actes réglementaires'],
        'HANDICAPEE (PERSONNE) - STATIONNEMENT': ['Voirie'],
        'HEURES D\'OUVERTURE': ['Autorisation d\'établissement'],
        'HOMOLOGATION DE TITRES ET GRADES ETRANGERS' : ['Autorisation d\'établissement'],
        'HONORABILITE PROFESSIONNELLE': ['Autorisation d\'établissement'],
        'HORAIRE MOBILE': ['Travail (comités mixtes d\'entreprise)'],
        'IMMATRICULATION DE VEHICULES': ['Transports'],
        IMPOTS: ['Compétence'],
        'INFORMATION PAR L\'ADMINISTRATION': ['Procédure administrative non contentieuse'],
        'INFORMATION SUR LE DROIT ETRANGER': ['Entraide judiciaire'],
        'INFORMATION EN MATIERE D\'ENVIRONNEMENT': ['Environnement'],
        'INFORMATION (acces au dossier)': ['Fonction publique', 'Marchés publics'],
        'INGENIEURS-CONSEILS': ['Autorisation d\'établissement'],
        'INONDATIONS (zones inondables)': ['Urbanisme'],
        'INSTITUT LUXEMBOURGEOIS DE REGULATION': ['Postes et Télécommunications', 'Régulation économique'],
        'INTERET A AGIR': ['Procédure contentieuse', 'Etablissements classés', 'Etrangers'],
        'INTERET GENERAL (notion)': ['Recours en annulation', 'Actes administratifs'],
        'INTERETS (SUBVENTION D\')': ['Fonction publique'],
        INTERPRETATION: ['Lois et règlements'],
        'JEUX DE HASARD': ['Autorisation d\'établissement'],
        JONCTION: ['Procédure contentieuse'],
        JOURNALISTE: ['Autorisation d\'établissement'],
        'JUGEMENT': ['Procédure contentieuse'],
        KARTING: ['Etablissements classés'],
        LANGUES: ['aussi Etrangers', 'Fonction publique'],
        'LEGITIME CONFIANCE': ['Lois et règlements'],
        'LIBERTE DU COMMERCE': ['Autorisation d\'établissement'],
        'LIBERTE RELIGIEUSE': ['Droits de l\'homme', 'Enseignement'],
        LICENCE: ['Transports'],
        LIQUIDATION: ['Autorisation d\'établissement'],
        LOTERIE: ['Autorisation d\'établissement'],
        'MAGISTRATURE (BIBLIOTHEQUE CENTRALE DE LA)': ['Actes administratifs'],
        MAITRISE: ['Autorisation d\'établissement'],
        'MARCHES PUBLICS': ['aussi Actes réglementaires', 'Procédure contentieuse (mesures provisoires)'],
        MEDECIN: ['Autorisation d\'établissement', 'Santé publique'],
        MEDIATEUR: ['Procédure administrative non contentieuse'],
        MEDICAMENTS: ['Santé publique'],
        MEMORIAL: ['Lois et règlements'],
        'MESURE DE PLACEMENT': ['Etrangers'],
        'MINISTRE (POUVOIRS DU)': ['Compétence', 'Lois et règlements'],
        'MISE A LA DISPOSITION DU GOUVERNEMENT': ['Etrangers', 'Droits de l\'homme'],
        'MOBILIER URBAIN': ['Communes'],
        MONUMENTS: ['Sites et monuments'],
        'MOTIVATION D\'UNE DECISION': ['Procédure administrative non contentieuse'],
        'MOYENS NOUVEAUX': ['Procédure contentieuse, sub Echange de mémoires'],
        NATIONALITE: ['Etrangers', 'Noms – Prénoms – Domicile – Etat civil – Nationalité'],
        NATURALISATION: ['Etrangers'],
        'NATURE (PROTECTION DE LA)': ['Environnement', 'Etablissements classés'],
        NOMINATION: ['Fonction publique'],
        '"NON BIS IN IDEM"': ['Droits de l\'homme', 'Fonction publique', 'Procédure contentieuse', 'Transports'],
        'NON-RETROACTIVITE': ['Lois et règlements'],
        NOTAIRES: ['Enseignement'],
        NOTIFICATION: ['Procédure contentieuse'],
        '"NUIT BLANCHE" (AUTORISATION DE)': ['Autorisation d\'établissement'],
        'OBLIGATIONS DE L\'ADMINISTRATION': ['Actes administratifs, sub Divers'],
        'OFFRE DE PREUVE': ['Procédure contentieuse'],
        'ORGANIGRAMME': ['Actes administratifs'],
        'ORGANISMES CONSULTATIFS': ['Procédure administrative non contentieuse'],
        OUVRIERS: ['Fonction publique', 'Compétence'],
        '"PATERE LEGEM"': ['Lois et règlements'],
        'PERMIS DE CONDUIRE': ['Transports'],
        'PERMIS A POINTS': ['Transports', 'Droits de l\'homme'],
        'PERMIS DE TRAVAIL': ['Travail'],
        'PERMISSION DE VOIRIE': ['Voirie'],
        'PERSONNE HANDICAPEE (STATIONNEMENT)': ['Voirie'],
        'PEINES (EXECUTION DES)': ['Actes administratifs', 'Compétence', 'Droits de l\'homme'],
        PHARMACIEN: ['Santé publique'],
        PIECES: ['Procédure contentieuse'],
        'PILOTE D\'AVION': ['Transports'],
        'PLAN D\'AMENAGEMENT': ['Urbanisme', 'Tutelle administrative', 'Actes réglementaires', 'Compétence'],
        POLICE: ['Fonction publique'],
        PORCHERIE: ['Etablissements classés'],
        'POUVOIRS DU JUGE': ['Recours en annulation'],
        'PRECAUTION (PRINCIPE DE)': ['Etablissements classés'],
        PRENOMS: ['Noms – Prénoms – Domicile – Etat civil – Nationalité'],
        PRESCRIPTION: ['Travail', 'Fonction publique'],
        PRESSE: ['Autorisation d\'établissement', 'Procédure contentieuse'],
        PREUVE: ['Procédure contentieuse', 'Actes administratifs'],
        'PRINCIPES GENERAUX DU DROIT': ['Lois et règlements'],
        'PRINCIPE DE PRECAUTION': ['Etablissements classés'],
        'PRINCIPE DE PROPORTIONNALITE': ['Lois et règlements'],
        'PROCEDURE CONTENTIEUSE': ['aussi sub Impôts'],
        PROFESSION: ['Autorisation d\'établissement'],
        'PROJET D\'AMENAGEMENT': ['Urbanisme', 'Tutelle administrative', 'Actes réglementaires', 'Compétence'],
        'PROPORTIONNALITE (PRINCIPE DE)': ['Recours en annulation', 'Lois et règlements', 'Etrangers'],
        'PROTECTION DE L\'ENVIRONNEMENT': ['Environnement', 'Etablissements classés'],
        'PROTECTION DE LA NATURE': ['Environnement', 'Etablissements classés'],
        'PROTECTION DES DONNEES': ['aussi Actes réglementaires'],
        'QUALIFICATION PROFESSIONNELLE': ['Autorisation d\'établissement'],
        'QUALITE POUR AGIR': ['Procédure contentieuse'],
        'QUOTAS LAITIERS': ['Agriculture'],
        RECLAMATION: ['Procédure administrative non contentieuse', 'Procédure contentieuse'],
        'RECOURS GRACIEUX': ['Procédure administrative non contentieuse', 'Procédure contentieuse'],
        'RECOURS HIERARCHIQUE': ['Procédure administrative non contentieuse'],
        'RECOURS EN REVISION': ['Actes administratifs', 'Procédure contentieuse'],
        'RECOURS (EFFET SUSPENSIF)': ['Procédure contentieuse'],
        'REEMPLOI (AIDES AU)': ['Travail'],
        'REFOULEMENT': ['Etrangers'],
        REFUGIES: ['Etrangers', 'Droits de l\'homme'],
        'REGISTRE DES DIPLOMES': ['Enseignement'],
        'REGISTRE DE LA POPULATION': ['Noms – prénoms – domicile – état civil – nationalité'],
        'REGLEMENT (en general)': ['Actes réglementaires', 'Lois et règlements', 'Compétence'],
        'REGLEMENT SUR LES BATISSES': ['Urbanisme'],
        'RELIGION (LIBERTE RELIGIEUSE)': ['Droits de l\'homme', 'Enseignement'],
        'REMEMBREMENT': ['Urbanisme'],
        'RENSEIGNEMENTS (SERVICE DE)': ['Fonction publique', 'Information'],
        REPRESENTATION: ['Procédure contentieuse'],
        'REQUETE INTRODUCTIVE D\'INSTANCE': ['Procédure contentieuse'],
        'RESEAU FERROVIAIRE': ['Voirie'],
        'RETENTION ADMINISTRATIVE': ['Etrangers', 'Droits de l\'homme'],
        'RETRAIT D\'UN ACTE ADMINISTRATIF': ['Actes administratifs', 'Procédure non contentieuse'],
        'RETRAITE (MISE A LA)': ['Fonction publique'],
        RETROACTIVITE: ['Actes administratifs', 'Lois et règlements'],
        RETROCESSION: ['Expropriation'],
        'REVISEUR D\'ENTREPRISES': ['Autorisation d\'établissement'],
        REVISION: ['Actes administratifs', 'Compétence', 'Procédure contentieuse'],
        '"SANS-PAPIERS" (REGULARISATION DES)': ['Etrangers'],
        'SCHENGEN (ACCORD DE)': ['Etrangers'],
        'SECRETAIRE DE DIRECTION': ['Fonction publique'],
        'SECURITE (COORDINATEUR DE)': ['Autorisation d’établissement'],
        SEPULTURE: ['Communes'],
        'SERVICE DE RENSEIGNEMENTS': ['Fonction publique', 'Lois et règlements'],
        SERVITUDES: ['Compétence', 'Urbanisme'],
        'SIGNATURE (DELEGATION DE)': ['Actes administratifs'],
        'SILENCE DE L\'ADMINISTRATION': ['Actes administratifs', 'Procédure contentieuse'],
        STAGE: ['Fonction publique'],
        SOURCES: ['Environnement'],
        SPECTACLES: ['Communes'],
        'STATIONNEMENT': ['Voirie'],
        'STATION-SERVICE': ['Etablissements classés', 'Urbanisme'],
        'STRUCTURE D\'ACCUEIL': ['Santé publique'],
        STUPEFIANTS: ['Santé publique'],
        'SUBSTITUTION DE MOTIFS': ['Procédure administrative non contentieuse', 'Recours en annulation'],
        'SUBVENTION D\'INTERETS': ['Fonction publique'],
        SUPERMARCHE: ['Etablissements classés'],
        'SYNDICAT DE CHASSE': ['Environnement'],
        'SYNDICAT DE COMMUNES': ['Communes'],
        'SYNDICAT DES TRAVAILLEURS': ['Procédure contentieuse (qualité pour agir)', 'Travail'],
        TAXES: ['Impôts'],
        TAXIS: ['Transports'],
        'TELECOMMUNICATIONS (CONTROLE DU SECTEUR DES)': ['Régulations économiques'],
        TELEDISTRIBUTION: ['Postes et Télécommunications'],
        TEMOIN: ['Procédure contentieuse'],
        'TITRES ETRANGERS (HOMOLOGATION DE)': ['Autorisation d\'établissement'],
        'TITRES DE SOCIETE (RETRAIT OU ACHAT)': ['Autorisation d’établissement'],
        TOMBE: ['Communes'],
        'TRAITE INTERNATIONAL': ['Lois et règlements'],
        'TRAITEMENT': ['Fonction publique'],
        TRANSACTION: ['Compétence'],
        'TRANSCRIPTION D\'UN ACTE DE MARIAGE': ['Communes'],
        TRAVAIL: ['Droits de l\'homme'],
        'TRAVAIL INTERIMAIRE': ['Autorisation d\'établissement'],
        'TUTELLE ADMINISTRATIVE': ['aussi Actes administratifs', 'Urbanisme'],
        TVA: ['Compétence'],
        URBANISME: ['aussi Etablissements classés', 'Procédure contentieuse (mesures provisoires)'],
        'VIE PRIVEE ET FAMILIALE': ['Droits de l\'homme', 'Etrangers'],
        VOISIN: ['Procédure contentieuse'],
        WHISTLEBLOWER: ['Travail'],
        'ZONES INONDABLES': ['Urbanisme'],
        'ZONE VERTE': ['Environnement', 'Compétence', 'Etablissements classés']
    };
    possibleKeys = Object.getOwnPropertyNames(this.possibleKeywords);

    constructor(public api: ApiService,
                public popCtrl: PopoverController,
                public platform: Platform) {
        super(true, popCtrl, platform);
        this.api.getTomeTypes().then(availableTypes => this.availableTypes = availableTypes,
            this.api.presentErr.bind(this.api));
    }

    searchTome() {
        this.api.getAvailableBooks({
            kind: this.kind,
            author: this.author,
            desc: this.desc,
            keywords: this.keywords,
            fulltext: this.kind === 'bulletin' ? undefined : this.fulltext
        }).then(availableBooks => this.availableBooks = availableBooks,
            this.api.presentErr.bind(this.api));
    }

    goTo(tome: Tome) {
        window.open(this.api.CONFIG.aws.s3 + 'pasicrisie-pdf/' + tome.kind + '/' + tome._id + '.pdf', '_blank');
    }

    doInfinite() {
        this.displays += 10;
    }
}
